version: "3.9"

services:
  rasa:
    build:
      context: .
      dockerfile: Dockerfile.rasa
    image: cetma-rasa-bot
    container_name: rasa-chatbot-cetma
    ports:
      - "8099:5005"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./config.yml:/app/config.yml
      - ./domain.yml:/app/domain.yml
      - ./credentials.yml:/app/credentials.yml
      - ./endpoints.yml:/app/endpoints.yml
      # Directory per file esportati
      - ./exports:/app/exports
    depends_on:
      - action_server
    environment:
      - RASA_DUCKLING_HTTP_URL=http://duckling:8000
    restart: unless-stopped


  action_server:
    build:
      context: .
      dockerfile: Dockerfile.actions
    image: cetma-action-server
    container_name: rasa-action-server-cetma
    ports:
      - "5055:5055"
    volumes:
      # Solo volume essenziali
      - ./data_persistent:/app/data_persistent
      - ./exports:/app/exports
    environment:
      - PYTHONPATH=/app
      - DATABASE_PATH=/app/data_persistent/cetma_bookings.db
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    # Healthcheck per verificare che il container sia ready
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5055/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

